// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbxZ0eXmUB9UrW0bEbJxO9sP7oha4xWbjSjc-8iiM71AX3EGLIbFDAls0HwG7jYhkuyzPg/exec";
